info:
  contact: {}
  description: This is a sample Server pets
  title: linktree API
  version: 0.1.0
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
